CREATE TABLE
    BOOK (
        BOOKID INT PRIMARY KEY,
        TITLE VARCHAR(100),
        AUTHOR VARCHAR(100),
        ISBN VARCHAR(50),
        PUBLISHER VARCHAR(100),
        PUBLICATION_DATE DATE,
        LOAD_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE
    STUDENT_BOOK (
        STUDENT_BOOK_ID INT PRIMARY KEY,
        STUDENTID INT,
        BOOKID INT,
        BORROW_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        RETURN_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        LOAD_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (STUDENTID) REFERENCES STUDENTS (STUDENTID),
        FOREIGN KEY (BOOKID) REFERENCES BOOK (BOOKID)
    );

INSERT INTO
    BOOK (
        BOOKID,
        TITLE,
        AUTHOR,
        ISBN,
        PUBLISHER,
        PUBLICATION_DATE
    )
VALUES
    (
        1,
        'The Catcher in the Rye',
        'J.D. Salinger',
        '978-0-316-76948-0',
        'Little, Brown and Company',
        '1951-07-16'
    );

SELECT
    *
FROM
    BOOK;